            </td></tr></tbody>
            </table>
          </font></center>
        </div>
        </td></tr>
        <tr><td colspan="5" style="background-color:rgb(214,226,242); text-align:center; font-size:60%" height="40">
          <a href="http://www.sl-automation.com/copyright.asp">Copyright</a> ? 2014-2016
          <a href="http://www.sl-automation.com/">武汉三联自动化有限责任公司</a> All rights reserved.
        </td></tr>
      </tbody>
    </table>
    </div>
    </body>